# Generated by Django 5.2 on 2025-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_SAV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('ordinateur', 'Ordinateur'), ('imprimante', 'Imprimante'), ('serveur', 'Serveur')], default='ordinateur', max_length=20),
        ),
    ]
