# Generated by Django 5.2 on 2025-05-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_SAV', '0002_machine_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandereparation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
